trajectory_joints:
  - id: aruco_1
    joint_values: [0.28, -2.55, -1.87, 0.19, 2.55, -1.34]
  - id: aruco_2
    joint_values: [0.19, -2.6, -1.31, -0.42, 2.58, -1.48]
  - id: aruco_3
    joint_values: [0.23, -3.02, -0.26, -0.98, 2.56, -1.41]
  - id: aruco_4
    joint_values: [0.24, -2.70, -1.08, -0.47, 2.56, -1.4]
  - id: aruco_5
    joint_values: [0.12, -3.08, -0.14, -1.22, 2.6, -1.60]
  - id: aruco_6
    joint_values: [0.08, -2.46, -1.47, -0.57, 2.62, -1.38]
  - id: aruco_7
    joint_values: [0.12, -2.25, -1.99, -0.17, 2.6, -1.27]